spring:
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27018}
      database: ${MONGODB_DATABASE:mongock-example}
      replica-set-name: ${MONGODB_REPLICA_SET_NAME:rs0}
      auto-index-creation: true
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
mongock:
  migration-scan-package: dev.example.mongock.configuration.database.migration
  transaction-enabled: true
server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: framework
